name: terraform-aws


on:
  push:
    branches: ["main"]
    paths:
      - "aws/**"
      - ".github/workflows/terraform-aws.yml"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_bucket_prefix: ${{ secrets.AWS_BUCKET_NAME }}

      - name: Terraform Apply (main only)
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}

